@startuml Conceitual

class Usuário {

id: int
nome: string
email: string
senha: string
dataDeCadastro: date
premium: Bool
}

class Freelancer {

categoria: string[]
subcategoria: string[]
precoHora: float
reputação: int
descricao: string
portfolio: string
}

class Cliente {

tipo: string
}

class Moderador {

id: int
}

class Proposta {

id: int
valor: float
descricao: string
status: string
data: date
}

class Projeto {

id: int
nome: string
categoria: string
descricao: string
dataDeCriacao: date
precoMin: float
precoMax: float
status: string
}

class Chat {

id: int
mensagens: string[]
data: date
}

class Avaliacao {

id: int
Classificação: int
Comentário: string
dataDaAvaliação: date
}

Usuário <|-- Moderador
Usuário <|-- Cliente
Usuário <|-- Freelancer


Avaliacao --> Usuário : Refere-se
Avaliacao --> Projeto: Refere-se

Usuário --> Avaliacao: Faz
Proposta --> Projeto: Pertence a
Freelancer --> Proposta: Faz Proposta
Freelancer --> Projeto: Participa em
Cliente --> Projeto: Cria
Moderador --> Projeto: Modera
Freelancer --> Chat: Participa em
Cliente --> Chat: Participa em
Moderador --> Chat: Participa em

@enduml