@startuml

left to right direction

actor "Freelancer" as g

actor "Cliente" as c

 

package Sistema { 

    g --> (Criar Perfil)
    c --> (Criar Perfil)
    g --> (Oferecer Serviços)
    g --> (Encontrar Cliente)
    g --> (Negociar serviços)
    g --> (Aceitar Serviço)
    g --> (Gerrenciar serviços)
    g --> (Entregar serviços)
    (Entregar serviços)..>(Receber Pagamento) :<include>
    g --> (Avaliar cliente) 

    
    c --> (Criar Perfil)
    c --> (Criar Serviços)
    c --> (Encontrar Freelancer)
    c --> (Negociar serviços)
    c --> (Contratar serviços)
    (Contratar serviços)..> (Realizar pagamento) :<include>
    c --> (Gerrenciar serviços)
    c --> (Receber serviços)
    c --> (Avaliar freelancer) 

}

 

 

 

@enduml

 

@enduml